sudo: false
language: node_js
node_js:
  - "6"

cache:
  yarn: true
  directories:
    - node_modules
    - packages/entity-browser/node_modules
    - packages/login/node_modules
    - packages/merge/node_modules
    - packages/tocco-test-util/node_modules
    - packages/tocco-theme/node_modules
    - packages/tocco-ui/node_modules
    - packages/tocco-ui-showcase/node_modules
    - packages/tocco-util/node_modules
    - .eslintcache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn
  - lerna bootstrap

script:
  - npm run lint
  - npm run flow
  - npm run test
  - npm run test:saucelabs

after_success:
  - npm run codecov
  - bash deployment/deploy_showcase.sh

env:
  global:
  - ENCRYPTION_LABEL: "49dedc788d53"
  - COMMIT_AUTHOR_EMAIL: "bot@tocco.ch"
